Feature/auth
cdcgi/user-service pull request #14
Opened 2020-12-01 03:37 UTC by fakhri007

2020-12-01 04:13 UTC, jacky-htg commented on doc/auth.md
> +username | string | jacky
request payloads cukup salah satu antara email dan username. menurut saya sebaiknya gunakan email saja.

2020-12-01 04:14 UTC, jacky-htg commented on doc/auth.md
> +For recycle your password, you need to input your username and email for sending an password recovery to your email.
just one input: email

2020-12-01 04:14 UTC, jacky-htg commented on doc/auth.md
> +    "username": "jacky",
remove input username, ust 1 input: email

2020-12-01 04:15 UTC, jacky-htg commented on doc/auth.md
> +- username : required and not empty
not need username input

2020-12-01 04:17 UTC, fakhri007 commented on doc/auth.md
> +username | string | jacky
baik pak

2020-12-01 04:17 UTC, jacky-htg commented on doc/auth.md
> +- email: required and not empty
need check email validation. You can use email pattern or better using [php filter email validation](https://www.php.net/manual/en/filter.filters.validate.php)

2020-12-01 04:18 UTC, jacky-htg commented on doc/auth.md
> +    "status_message": "username is required",
email is required

2020-12-01 04:18 UTC, jacky-htg commented on doc/auth.md
> +    "status_message": "username is required",
email is required

2020-12-01 04:19 UTC, jacky-htg commented on doc/auth.md
> +#### Case : Negative Case 3
invalid case for Negative case 3 because no need username input

2020-12-01 04:19 UTC, jacky-htg commented on doc/auth.md
> +#### Case : Negative Case 4
invalid case for Negative case 4 because no need username input

2020-12-01 04:20 UTC, jacky-htg commented on doc/auth.md
> +    "username": "asal",
remove username input

2020-12-01 04:20 UTC, jacky-htg commented on doc/auth.md
> +    "username": "asal",
remove username input

2020-12-01 04:21 UTC, jacky-htg commented on doc/auth.md
> +    "status_message": "Invalid username/email",
invalid email

2020-12-01 04:22 UTC, jacky-htg commented on doc/auth.md
> +    "status_code": "cdc-404",
cdc-400 because it's email format bad request

2020-12-01 04:22 UTC, jacky-htg commented on doc/auth.md
> +Response HTTP Status Code : 404
status code: 400 becaus it's email format bad request

2020-12-01 04:24 UTC, jacky-htg commented on doc/auth.md
> +
Add one Case for negative case email not found in database. the email input is valid but there is no record in database.

2020-12-01 04:27 UTC, jacky-htg commented on doc/auth.md
> +    "username": "jacky",
remove username input

2020-12-01 04:30 UTC, jacky-htg commented on doc/auth.md
> +
You need create new table forgot password for store the link of forgot password request. Please show the sql script below.

2020-12-01 04:37 UTC, jacky-htg requested changes
POST /forgot-password
1. need 1 input only : email
2. add sql script for create forgot_passwords table
3. add logic step by step
4. add negative case for scenario not found in database. the email input is valid, but no record in the database.

2020-12-01 04:37 UTC, jacky-htg commented on doc/auth.md
> +*if any special logic, please write down the logic here. thanks*
1. Validate email input
2. Store the link forgot password to forgot_passwords table.
3. Send email reset password link to user

2020-12-01 05:09 UTC, jacky-htg requested changes
many my feedback has been resolved. You need to resolve two point below:
1. add sql script create forgot_password tables.
2. add step by step logic

2020-12-01 08:33 UTC, jacky-htg approved these changes

2020-12-01 12:10 UTC, jacky-htg commented
@fakhri007 Please consider to change email field to user_id in table of forgot_passwords. user_id is foreignKey to users table.

2020-12-02 05:49 UTC, jacky-htg requested changes
1. change-password need user_id/email/username in payload request, so we know who is changing the password.
2. resolve my comments in the review

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +old_password | string | jakaRTa!2020
add users_id or username or email (choose one) on the request

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +    "old_password": "jakaRTa!2020",
add users_id or username or email on the request

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +3. check if old password input is same like on database.
- check if username/email/user_id exist in database and get password from database based on username/email/user_id
- compare old password from request with password from database

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +
- new password = re new password
- old password = current password from db

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +    "status_message": "old password is required",
username/email/user_id is required

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +    "status_message": "old password is required",
username/email/user_id is required

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +    "status_message": "old password is empty",
email is required

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +    "old_password": ""
"email": ""

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +
4. check token is valid ? is token is exist? is token expired? is token used?

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +
- check strong password
- token validation

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +### Scenario Test
where is token in your scenario test?

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +
show users tables

2020-12-02 05:49 UTC, jacky-htg commented on doc/auth.md
> +
show users tables and forgot_passwords table

2020-12-03 05:21 UTC, jacky-htg requested changes

2020-12-03 05:21 UTC, jacky-htg commented on doc/auth.md
> +<<<<<<< HEAD
Please fix the conflict below

2020-12-03 05:24 UTC, jacky-htg requested changes
1. Please fix the conflict below
2. show users table on the change-password endpoint
3. show users table and forgot_passwords table on reset-password endpoint

2020-12-03 07:49 UTC, jacky-htg requested changes
Please resolve my comments below. thanks.

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +
add email header

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +user_id | string | 1
need no user_id since we have email in header

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +    "user_id : 1,
remove user_id

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +3. check if user_id exist in database and get password from database based on user_id
replace user_id with email in header

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +- user id: required and not empty
need no user_id validation

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +    "status_message": "user not found",
old_password

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +    "status_code": "cdc-404",
cdc-400

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +Response HTTP Status Code : 404
400

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +Response HTTP Status Code : 404
400

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +    "status_code": "cdc-404",
cdc-400

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +#### Case : Negative Case 3
invalid case

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +#### Case : Negative Case 4
invalid case

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +    "user_id": 1
remove user_id

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +    "user_id": 1
remove user_id

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +    "user_id": 1
remove user_id

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +    "user_id": 1
remove user_id

2020-12-03 07:49 UTC, jacky-htg commented on doc/auth.md
> +    "user_id": 1
remove user_id

2020-12-03 08:36 UTC, jacky-htg approved these changes

2020-12-04 07:21 UTC, jacky-htg commented on doc/auth.md
> +Email | application/json
The example value of Email is rijal.asep.nugroho@gmail.com, not application/json

2020-12-05 10:15 UTC, msyuniarto requested changes

2020-12-05 10:15 UTC, msyuniarto commented on doc/auth.md
> +    "token": "c4ca4238a0b923820dcc509a6f75849b"
tambahin koma yak

2020-12-05 10:15 UTC, msyuniarto commented on doc/auth.md
> +    "token": "c4ca4238a0b923820dcc509a6f75849b"
tambahin koma yak

2020-12-05 10:15 UTC, msyuniarto commented on doc/auth.md
> +    "token": "c4ca4238a0b923820dcc509a6f75849b"
tambahin koma yak

2020-12-05 10:15 UTC, msyuniarto commented on doc/auth.md
> +    "token": "c4ca4238a0b923820dcc509a6f75849b"
tambahin koma yak

2020-12-05 10:15 UTC, msyuniarto commented on doc/auth.md
> +          "email": "jacky@gmail.com",
baris terakhir gak butuh koma

2020-12-07 03:18 UTC, msyuniarto requested changes

2020-12-07 03:18 UTC, msyuniarto commented on doc/auth.md
> +          "email": "jacky@gmail.com",
baris terakhir gak butuh koma

2020-12-07 03:19 UTC, fakhri007 commented on doc/auth.md
> +          "email": "jacky@gmail.com",
ga ngaruh

2020-12-07 03:42 UTC, msyuniarto approved these changes

2020-12-08 01:55 UTC, ferrystiawan approved these changes

2020-12-08 01:58 UTC, merged