[#3] Update Regions Documentation and add a figure of regions table
cdcgi/user-service pull request #16
Opened 2020-12-02 04:40 UTC by msyuniarto

2020-12-02 06:18 UTC, wahablie approved these changes
untuk kolom id gunakan char(36), auto generate

2020-12-03 07:11 UTC, jacky-htg requested changes
Please resolve my comment below. Thanks.

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +#### Case : Negative Case 8
invalid case since no need company_id in request body

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +    "id": "7",
remove id

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +#### Case : Positive Case 1
invalid case since no need id in request body

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +    "id": "7",
remove id

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +    "id": "7",
remove id

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +#### Case : Positive Case 4
invalid case since no need company_id in request body

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +
add header email

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +### Request Payloads
no need request body

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +Content-Type | application/json
there is no json content body, so change the Content-Type to *

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +400 | Bad Request | Bad request payload
there is no bad request

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +404 | Not Found | User not found in database
region no found in database

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +200 | OK | OK
for delete we send 204 http status.
204 | No content | No content

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +#### Validation
you need  no validation

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +#### Case : Negative Case 1
invalid case since there is no id request in json body

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +#### Case : Negative Case 2
invalid case since there is no id request in json body

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +#### Case : Negative Case 3
invalid case since there is no id request in json body

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +#### Case : Negative Case 4
invalid case since there is no id request in json body

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +    "id": "7",
remove request paylod

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +Response HTTP Status Code : 200
204

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +    "status_code": "CDC-200",
CDC-204

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +200 | OK | OK
201 Created

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +    "status_code": "CDC-200",
CDC-201

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +Response HTTP Status Code : 200
201

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +    "status_code": "CDC-200",
CDC-201

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +400 | Bad Request | Bad request payload
there is no bad request since you need no request body

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +404 | Not Found | User not found in database
Region not found in database

2020-12-03 07:11 UTC, jacky-htg commented on doc/regions.md
> +404 | Not Found | User not found in database
Region

2020-12-04 02:43 UTC, vdennis requested changes
kurang coma bos

2020-12-04 02:43 UTC, vdennis commented on doc/regions.md
> +    "name": "Auto Moro Dewe"
kurang coma bos

2020-12-04 12:11 UTC, jacky-htg requested changes

2020-12-04 12:11 UTC, jacky-htg commented on doc/regions.md
> +Response Payload :
remove response payload

2020-12-04 15:29 UTC, jacky-htg commented on doc/regions.md
> +- region_code : required and not empty
and unique

2020-12-04 15:29 UTC, jacky-htg commented on doc/regions.md
> +        "modified" : "2020-12-02 09:03:44",
kelebihan koma

2020-12-04 15:29 UTC, jacky-htg commented on doc/regions.md
> +        "modified" : "2020-12-02 09:03:44",
the last line does not need comma

2020-12-04 15:29 UTC, jacky-htg commented on doc/regions.md
> +        "modified" : "2020-12-02 09:03:44",
the last line does not need comma

2020-12-04 15:29 UTC, jacky-htg commented on doc/regions.md
> +        "modified" : "2020-12-02 09:03:44",
the last line does not need comma

2020-12-04 15:29 UTC, jacky-htg commented on doc/regions.md
> +        "modified" : "2020-12-02 09:03:44",
the last line does not need comma

2020-12-04 15:29 UTC, jacky-htg commented on doc/regions.md
> +        "modified" : "2020-12-02 10:03:44",
the last line does not need comma

2020-12-04 15:29 UTC, jacky-htg commented on doc/regions.md
> +        "modified" : "2020-12-02 10:03:44",
the last line does not need comma

2020-12-04 17:33 UTC, jacky-htg approved these changes

2020-12-05 09:13 UTC, vdennis approved these changes

2020-12-06 03:51 UTC, jacky-htg requested changes
- remove company_code from regions table. You should have one foreign key to companies table.
- field of kunci. can you explain what it is for?

2020-12-06 06:57 UTC, jacky-htg approved these changes

2020-12-06 06:58 UTC, merged