[#1] Update documentation kios
cdcgi/user-service pull request #17
Opened 2020-12-02 08:59 UTC by iputumj

2020-12-03 07:35 UTC, jacky-htg requested changes
Please resolve my comments below. thanks.

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +
add email header for user login information

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +404 | Not Found | User not found in database
branch not found in database

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +200 | OK | OK
201 created

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +- branch_code   : required and not empty
check branch_code is owned by user login?

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +404 | Not Found | User not found in database
add 403 Forbidden status code, for branch_code is not owned by user login

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Response HTTP Status Code : 404
400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "status_code": "cdc-404",
CDC-400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Response HTTP Status Code : 404
400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "status_code": "cdc-404",
CDC-400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Response HTTP Status Code : 404
400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "status_code": "cdc-404",
cdc-400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Response HTTP Status Code : 400
404

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "status_code": "cdc-400",
cdc-404

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +
Add negative case for 403 forbidden when the brach_code is not owned by user login.

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +
add header email

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +id | string | 1
remove id, since id exist in path

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "id": 1,
remove id

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +404 | Not Found | User not found in database
kios not found

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +404 | Not Found | User not found in database
403 forbidden when branch_code is not owned by user login

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +- id            : required and not empty
remove id

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +- branch_code   : required and not empty
check branch_code is owned by user login

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "status_message": "id is required",
kios_name is required

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "status_message": "id is required",
kios_name is required

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +#### Case : Negative Case 3
inalid case since need no id in request payload

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "status_message": "id not found",
address is requeired

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Response HTTP Status Code : 404
400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "status_code": "cdc-404",
cdc-400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "id": "1",
remove id

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Response HTTP Status Code : 404
400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "status_code": "cdc-404",
cdc-400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "id": "1",
remove id

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Response HTTP Status Code : 404
400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "status_code": "cdc-404",
cdc-400

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "id": "1",
remove id

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Response HTTP Status Code : 400
404

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "status_code": "cdc-400",
cdc-404

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +
add negative case 403 forbidden when branch_code not owned by user login

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "id": 1,
remove id

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +    "id": 1,
remove id

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +
add email header

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +### Request Payloads
need no request payload

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +404 | Not Found | User not found in database
kios not found

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +404 | Not Found | User not found in database
403 kios id not owned by user login

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +- id : required and not empty
remove id

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +- id : required and not empty
check id of kios is owned by user login

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +#### Case : Negative Case 1
invalid case

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +#### Case : Negative Case 2
invalid case

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +#### Case : Negative Case 3
invalid case

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +#### Case : Negative Case 4
invalid case

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Request Payload :
delete request payload

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +
add email header

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +### Request Payloads
there is no request payload

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +404 | Not Found | User not found in database
kios not found

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +404 | Not Found | User not found in database
403 forbidden when id is not owned by user login

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +200 | OK | OK
204 no content

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +- id: required and not empty
- remove id
- check id in path is owned by user login

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +#### Case : Negative Case 1
invalid case

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +#### Case : Negative Case 2
invalid case

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +#### Case : Negative Case 3
invalid case

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +#### Case : Negative Case 4
invalid case

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Request Payload :
remove request payload

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +response HTTP Status Code : 200
204

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Response Payload :
there is no response payload

2020-12-03 07:35 UTC, jacky-htg commented on doc/kios.md
> +Content-Type | application/json
Content-Type | *

2020-12-04 12:17 UTC, jacky-htg requested changes

2020-12-04 12:17 UTC, jacky-htg commented on doc/kios.md
> +
email | rijal.asep.nugroho@gmail.com

2020-12-04 12:17 UTC, jacky-htg commented on doc/kios.md
> +200 | OK | OK
i mean remove 200 and change with 201. for add will be created a new record, so, the success status code not just 200 ok, but specific status code : 201 created

2020-12-04 12:24 UTC, jacky-htg requested changes

2020-12-04 12:24 UTC, jacky-htg commented on doc/kios.md
> +
email | rijal.asep.nugroho@gmail.com

2020-12-04 12:24 UTC, jacky-htg commented on doc/kios.md
> +
Email | rijal.asep.nugroho@gmail.com

2020-12-04 12:24 UTC, jacky-htg commented on doc/kios.md
> +Email | application/json
email | rijal.asep.nugroho@gmail.com

2020-12-04 12:24 UTC, jacky-htg commented on doc/kios.md
> +400 | Bad Request | Bad request payload
remove bad request

2020-12-04 12:24 UTC, jacky-htg commented on doc/kios.md
> +200 | OK | OK
remove 200 since we return 204 for success no content

2020-12-04 12:24 UTC, jacky-htg commented on doc/kios.md
> +{
there is no 400 bad equest

2020-12-04 12:24 UTC, jacky-htg commented on doc/kios.md
> +{
there is no 200 ok. if success please sent no content in body. You need no send anything.

2020-12-04 12:24 UTC, jacky-htg commented on doc/kios.md
> +```
remove request payload

2020-12-05 10:04 UTC, msyuniarto requested changes

2020-12-05 10:04 UTC, msyuniarto commented on doc/kios.md
> +    "kios_name": "kalimantan"
kurang koma

2020-12-05 10:04 UTC, msyuniarto commented on doc/kios.md
> +    "kios_name": "kalimantan"
kurang koma

2020-12-05 10:04 UTC, msyuniarto commented on doc/kios.md
> +    "address": "jl. k. h. moch mansyur no. 32 jembatan 5"
kurang koma

2020-12-05 10:04 UTC, msyuniarto commented on doc/kios.md
> +    "kios_name": "kalimantan"
kurang koma

2020-12-05 10:04 UTC, msyuniarto commented on doc/kios.md
> +    "address": "jl. k. h. moch mansyur no. 32 jembatan 5"
kurang koma

2020-12-05 10:04 UTC, msyuniarto commented on doc/kios.md
> +    "kios_name": "kalimantan"
kurang koma

2020-12-05 10:04 UTC, msyuniarto commented on doc/kios.md
> +    "address": "jl. k. h. moch mansyur no. 32 jembatan 5"
kurang koma

2020-12-05 10:44 UTC, msyuniarto approved these changes

2020-12-05 13:25 UTC, jacky-htg requested changes

2020-12-05 13:25 UTC, jacky-htg commented on doc/kios.md
> +
- you have 2 foreign key to other table : id and code. You should use one foreignKey, so remove code foreign key like branch_code, company-code, and warehouse_code.
- field of kunci. can you explain detail the field? documentation readers don't know what this is for

2020-12-05 13:25 UTC, jacky-htg commented on doc/kios.md
> +    "address": "jl. bekasi timur raya no. 159 A",
the last line does not need comma

2020-12-05 13:25 UTC, jacky-htg commented on doc/kios.md
> +        "address": "jl. bekasi timur raya no. 159 A"
need comma : 
"address": "jl. bekasi timur raya no. 159 A",

2020-12-05 13:25 UTC, jacky-htg commented on doc/kios.md
> +400 | Bad Request | Bad request payload
there is no request, so there is no 400 response. remove this line.

2020-12-05 13:25 UTC, jacky-htg commented on doc/kios.md
> +{
204 no content. it's mean really no content, so you shouldn't have response. delete all response in body if the response status code is 204.

2020-12-08 01:05 UTC, jacky-htg approved these changes

2020-12-11 06:48 UTC, dzakitajudin approved these changes

2020-12-14 08:23 UTC, merged