[#5] Update Companies Documentation and add a figure of companies table
cdcgi/user-service pull request #18
Opened 2020-12-04 04:36 UTC by AhmadGozali19

2020-12-04 05:51 UTC, jacky-htg requested changes
please resolve my comments below. thanks.

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +
Add View endpoint

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +404 | Not Found | User not found in database
remove 404

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +id | string | 5
remove id. use from path.

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id":"5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +404 | Not Found | User not found in database
Company not found

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +200 | OK | OK
201 Created

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +- id : required and not empty
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +- company_code : required and not empty
unique

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +- company_code : required and not empty
unique

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "status_message": "id is required",
replace id with ...

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +#### Case : Negative Case 3
invalid case since we need no id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +#### Case : Negative Case 4
invalid case since we need no id. but we need the not found scenario by grab id from path.

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id": "5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id": "5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id": "5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id": "5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id": "5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id": "5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id": "5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id": "5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id": "5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id": "5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +    "id": "5",
remove id

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +Content-Type | application/json
Content-Type : *

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +### Request Payloads
no request payload

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +{
no request payload

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +404 | Not Found | User not found in database
company not found

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +200 | OK | OK
204 no content

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +{
no content in body

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +- id : required and not empty
no request payload

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +#### Case : Negative Case 1
invalid case

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +#### Case : Negative Case 2
invalid case

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +#### Case : Negative Case 3
invalid case

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +#### Case : Negative Case 4
invalid case. but we need scenario case for company not found. grab id from path.

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +Request Payload :
no request payload

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +Response HTTP Status Code : 200
204

2020-12-04 05:51 UTC, jacky-htg commented on doc/companies.md
> +Response Payload :
no response payload

2020-12-08 01:21 UTC, jacky-htg requested changes

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +![](./Companies.png)
remove field of kunci

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +200 | OK | OK
remove 200 OK since we use 201 Created

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +Response HTTP Status Code : 200
201

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +        "id":"5",
id --> uuid, not number string

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +        "id":"5",
id --> uuid, not number string

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +        "id":"5",
id --> uuid, not number string

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +      "id":"5",
id --> uuid, not number string

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +        "id":"5",
id --> uuid, not number string

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +#### Case : Negative Case 1
invalid case, if there is no request, it's mean there is no data updated.

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +        "id":"5",
id --> uuid, not number string

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +        "id":"5",
id --> uuid, not number string

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +        "id":"5",
id --> uuid, not number string

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +        "id":"5",
id --> uuid, not number string

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +        "id":"5",
id --> uuid, not number string

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +200 | OK | OK
remove 200 OK since we use 204 no content

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +{
remove all response payload. 204 no content it;s mean really no content ion body response.

2020-12-08 01:21 UTC, jacky-htg commented on doc/companies.md
> +```
remove response

2020-12-08 02:47 UTC, msyuniarto requested changes

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +tgl_kukuh | date | 12
apakah bisa type date bisa menerima value selain date?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +    "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +- company_code : unique and not empty
di screnario test, ada company_code is required, mungkin bisa ditambahkan di baris ini

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +        "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +    "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +        "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +        "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +      "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +tgl_kukuh | date | 12
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +    "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +        "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +        "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +        "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +        "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +        "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 02:47 UTC, msyuniarto commented on doc/companies.md
> +        "tgl_kukuh": "12",
type date, value 12 apakah bisa?

2020-12-08 07:43 UTC, msyuniarto requested changes

2020-12-08 07:43 UTC, msyuniarto commented on doc/companies.md
> +400 | Bad Request | Bad request payload
untuk delete sepertinya tidak butuh http code 400, karena tidak ada request payloads

2020-12-08 07:43 UTC, msyuniarto commented on doc/companies.md
> +
add header email

2020-12-08 07:43 UTC, msyuniarto commented on doc/companies.md
> +
add header email

2020-12-08 07:43 UTC, msyuniarto commented on doc/companies.md
> +
add header email

2020-12-08 07:43 UTC, msyuniarto commented on doc/companies.md
> +
add header email

2020-12-08 08:13 UTC, jacky-htg requested changes

2020-12-08 08:13 UTC, jacky-htg commented on doc/companies.md
> +#### Case : Negative Case 1
remove this scenario because it is invalid case.

2020-12-08 08:13 UTC, jacky-htg commented on doc/companies.md
> +#### Case : Negative Case 2
remove this scenario because it's invalid case. no param request, it's mean no data changed.

2020-12-08 09:05 UTC, msyuniarto approved these changes

2020-12-10 16:42 UTC, jacky-htg requested changes
add endpoint for get list of companies with pagination. GET /companies 

### Param Query
Name | Example Value | Description
--- | --- | ---
search | jawara | keyword for search companies. default is empty.
page | 1 | current page. default 1.
limit | 20 | limit data in 1 pages. default 20.
order | companies.name | order of list. default companies.id
sort | asc | sort of list. option value is asc|desc. default value is desc

Example URL : GET /companies?search=jawara&order=companies.name

### Response Payload
```
{
    "status_code": "cdc-200",
    "status_message": "sucsess",
    "data": {
        "companies": [
            {
                "id":"5e8d6470-f654-24c8-93ac-332e6c3dra2e",
                "company_code": "TC",
                "name": "Test Company",
                "address": "JL. Test Company",
                "npwp": "123",
                "nomor_kukuh": "123",
                "tgl_kukuh": "2020-12-08",
                "phone_num": "021",
                "fax_num": "021",
                "seri_pajak": "12",
                "kota": "JAKARTA"
            }
        ],
        "pagination": {
            "search": "",
            "page": 1,
            "limit": 20,
            "order": "companies.name",
            "sort": "desc",
            "count": 100
        }
    }
}
```
 
there is no 404 response. If result is empty, response status code is 200, with body response payload :
```
{
    "status_code": "cdc-200",
    "status_message": "sucsess",
    "data": {
        "companies": [],
        "pagination": {
            "search": "",
            "page": 1,
            "limit": 20,
            "order": "companies.name",
            "sort": "desc",
            "count": 0
        }
    }
}
```

2020-12-10 16:42 UTC, jacky-htg commented on doc/companies.md
> +
add endpoint for get list of companies with pagination. GET /companies 

### Param Query
Name | Example Value | Description
--- | --- | ---
search | jawara | keyword for search companies. default is empty.
page | 1 | current page. default 1.
limit | 20 | limit data in 1 pages. default 20.
order | companies.name | order of list. default companies.id
sort | asc | sort of list. option value is asc|desc. default value is desc

Example URL : GET /companies?search=jawara&order=companies.name

### Response Payload
```
{
    "status_code": "cdc-200",
    "status_message": "sucsess",
    "data": {
        "companies": [
            {
                "id":"5e8d6470-f654-24c8-93ac-332e6c3dra2e",
                "company_code": "TC",
                "name": "Test Company",
                "address": "JL. Test Company",
                "npwp": "123",
                "nomor_kukuh": "123",
                "tgl_kukuh": "2020-12-08",
                "phone_num": "021",
                "fax_num": "021",
                "seri_pajak": "12",
                "kota": "JAKARTA"
            }
        ],
        "pagination": {
            "search": "",
            "page": 1,
            "limit": 20,
            "order": "companies.name",
            "sort": "desc",
            "count": 100
        }
    }
}
```
 
there is no 404 response. If result is empty, response status code is 200, with body response payload :
```
{
    "status_code": "cdc-200",
    "status_message": "sucsess",
    "data": {
        "companies": [],
        "pagination": {
            "search": "",
            "page": 1,
            "limit": 20,
            "order": "companies.name",
            "sort": "desc",
            "count": 0
        }
    }
}
```

2020-12-14 04:18 UTC, jacky-htg commented on doc/companies.md
> +        "id":"5e8d6470-f654-24c8-93ac-332e6c3dra2e",
{

2020-12-14 04:18 UTC, jacky-htg commented on doc/companies.md
> +      ],
}

2020-12-14 04:18 UTC, jacky-htg commented on doc/companies.md
> +      "companies" : [
companies are array of company object. please wrap the company data using {}

2020-12-15 03:08 UTC, jacky-htg requested changes
please resolve your code on file doc/companies.md line 900. 
companies are array of company object. please wrap the company data using {}

2020-12-15 03:55 UTC, jacky-htg approved these changes

2020-12-15 09:15 UTC, vdennis approved these changes

2020-12-17 14:49 UTC, merged